<a href="https://colab.research.google.com/github/vishal77777/ML-related/blob/main/handling_numerical_data_using_sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#rescaling a feature that to bring a value to the desired form
import numpy as np
from sklearn import preprocessing as pre
feature=np.array([[-500.5],
                  [-100.1],
                  [0],
                  [100.1],
                  [900.9]])
min_max_scale = pre.MinMaxScaler(feature_range=(0,1))
scaled=min_max_scale.fit_transform(feature)
scaled

"""MIN MAX FEATURE IS USED FOR THE SCALING OF NUMBERS IN THE ARRAY TO BE OF THE RANGE 0,1
MIN_MAX=  Xi-min(x)/max(x)-min(x)   for example from the array:
900.9-(-500.5)/900.9-(-500.5) = 1     """

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [ ]:
#standardizing a feature --bring the feature to have a mean of 0 and standard deviation of 1
#value will be in range from (-1,1)

x=np.array([[-500.5],
                  [-100.1],
                  [0],
                  [100.1],
                  [900.9]])
scaler=pre.StandardScaler()
standardized=scaler.fit_transform(x)

standardized , standardized.std(),standardized.mean(),standardized.min()

(array([[-1.26687088],
        [-0.39316683],
        [-0.17474081],
        [ 0.0436852 ],
        [ 1.79109332]]), 1.0, 0.0, -1)

In [ ]:
# robust scaler- to find the outlier of the data or the value which does relate 
# to the pattern of values in the array
robust=pre.RobustScaler()
robust.fit_transform(x)

array([[-2.5],
       [-0.5],
       [ 0. ],
       [ 0.5],
       [ 4.5]])

In [ ]:
#normalizing the feature according to each of the values
# L1 PARAMETER = MANHATTAN NORM
# L2 =EUCLIDEAN NORM (DISTANCE)
# 
y=np.array([[0.5,0.5],
            [1.2,1.3],
            [5.3,6.4]])
normalizer=pre.Normalizer("l1")

normalizerS=pre.Normalizer("l2")

print("l1, where sum of the value is 1,\n",(normalizer.fit_transform(y)))
print("l2, whereit is the distance between each individual feature,\n",normalizerS.fit_transform(y))

l1, where sum of the value is 1,
 [[0.5        0.5       ]
 [0.48       0.52      ]
 [0.45299145 0.54700855]]
l2, whereit is the distance between each individual feature,
 [[0.70710678 0.70710678]
 [0.6782801  0.73480344]
 [0.63781397 0.77019046]]
